version: '3.8'

services:
  listify-app:
    build: .
    image: listify-app:latest
    container_name: listify_app_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs