spring:
  config:
    import: classpath:env.yml
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/, file:${file.upload-dir}
  cache:
    cache-names: cities, categories
    caffeine:
      spec: >
        maximumSize=500, 
        expireAfterWrite=60m
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
app:
  jwt:
    secret: ${jwt.secret}
    expiration-ms: ${jwt.expiration-ms}
upload:
  path: ./uploads