spring:
  flyway:
    enabled: true
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/, file:${FILE_UPLOAD_DIR}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    expiration-ms: ${JWT_EXPIRATION_MS}
    private-key-path: file:./keys/private_key.pem
    public-key-path: file:./keys/public_key.pem
  cors:
    allowed-origins: ${ORIGINS}
upload:
  path: ${FILE_UPLOAD_DIR:./uploads}
  allowed-mime-types: image/jpeg, image/png, image/gif
