spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
logging:
  level:
    ROOT: INFO
    com.tech.listify: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
server:
  shutdown: graceful
